namespace IitOtdrLibrary
{
    public enum ServiceFunctionFirstParam
    {
        Unit = 1,
        Lmax = 2,
        L1 = 3,
        L2 = 4,
        Res = 5,
        Pulse = 6,
        Navr = 7,
        Time = 8,
        IsTime = 9,
        Gi = 10,
        Ri = 10,
        Bc = 11,
        HiRes = 12,
        LoPow = 13,
        LowPow = 13,
        Refresh = 14,
        WlEnabled = 15,
        Filter = 16,
        L1Val = 17,
        L2Val = 18,
        LmaxVal = 72,
        PulseVal = 73,
        NavrVal = 74,
        MaxLmax = 75,
        MaxPulse = 76,
        TimeVal = 77,
        Conn = 78,
        OverrideScaleAvr = 79,
        ScaleAvr = 80,
        ScaleAvrVal = 81,
        DwdmChannel = 82,
        FastAvrNumber = 83,

        ActiveUnit = 20,
        ActiveLmax = 21,
        ActiveL1 = 22,
        ActiveL2 = 23,
        ActiveRes = 24,
        ActivePulse = 25,
        ActiveNavr = 26,
        ActiveTime = 27,
        ActiveIsTime = 28,
        ActiveGi = 29,
        ActiveRi = 29,
        ActiveBc = 30,
        ActiveHiRes = 31,
        ActiveLoPow = 32,
        ActiveLowPow = 32,
        ActiveRefresh = 33,
        ActiveWlEnabled = 34,
        ActiveFilter = 35,
        ActiveL1Val = 36,
        ActiveL2Val = 37,
        ActiveLmaxVal = 92,
        ActivePulseVal = 93,
        ActiveNavrVal = 94,
        ActiveTimeVal = 95,
        ActiveConn = 96,
        ActiveOverrideScaleAvr = 97,
        ActiveScaleAvr = 98,
        ActiveScaleAvrVal = 99,
        ActiveDwdmChannel = 100,
        ActiveFastAvrNumber = 101,

    }
}
